@PREFIX=http://localhost:3000/api/v1

GET {{PREFIX}}/questions

### 

GET {{PREFIX}}/questions/122

###

POST {{PREFIX}}/questions
Content-Type: application/json

{
    "text": "How are you?",
    "authorId": 1,
    "date": "2026-03-17"
}